In [2]:
#Consider the below code to answer further questions:

import numpy as np
list_ = [1,2,3,4,5]
array_list = np.array(object = list_)

In [3]:
array_list

array([1, 2, 3, 4, 5])

In [4]:
# Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code
# to print the data types of both the variables.

In [5]:
import numpy as np

# Assuming list_ is a Python list
list_ = [1, 2, 3, 4, 5]

# Convert list_ to a NumPy array
array_list = np.array(list_)

# Print data types
print("Data type of list_:", type(list_))
print("Data type of array_list:", type(array_list))


Data type of list_: <class 'list'>
Data type of array_list: <class 'numpy.ndarray'>


In [6]:
# Q2. Write a code to print the data type of each and every element of both the variables list_ and
# arra_list.

In [7]:
import numpy as np

# Assuming list_ is a Python list
list_ = [1, 2, 3, 4, 5]

# Convert list_ to a NumPy array
array_list = np.array(list_)

# Print data types of each element in list_
print("Data types of elements in list_:")
for item in list_:
    print(type(item))

# Print data types of each element in array_list
print("\nData types of elements in array_list:")
for item in np.nditer(array_list):
    print(type(item.item()))


Data types of elements in list_:
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>

Data types of elements in array_list:
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>


In [8]:
# Q3. Considering the following changes in the variable, array_list:
# array_list = np.array(object = list_, dtype = int)
# Will there be any difference in the data type of the elements present in both the variables, list_ and
# arra_list? If so then print the data types of each and every element present in both the variables, list_
# and arra_list.

In [9]:
#Answer:

#yes, there would be a difference in the data types of the elements present in list_ and array_list after this change. By specifying the dtype=int parameter when creating the NumPy array array_list, you're explicitly setting the data type of the elements to be integers.

In [10]:
import numpy as np

# Assuming list_ is a Python list
list_ = [1, 2, 3, 4, 5]

# Convert list_ to a NumPy array with dtype=int
array_list = np.array(object=list_, dtype=int)

# Print data types of each element in list_
print("Data types of elements in list_:")
for item in list_:
    print(type(item))

# Print data types of each element in array_list
print("\nData types of elements in array_list:")
for item in np.nditer(array_list):
    print(type(item.item()))


Data types of elements in list_:
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>

Data types of elements in array_list:
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>


In [11]:
#Consider the below code to answer further questions:

import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)

In [12]:
num_array

array([[1, 2, 3],
       [4, 5, 6]])

In [15]:
# Q4. Write a code to find the following characteristics of variable, num_array:
# (i) shape
# (ii) size

In [16]:
import numpy as np

# Assuming num_array is your NumPy array
num_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Find the shape of num_array
shape = num_array.shape

# Find the size of num_array
size = num_array.size

print("Shape of num_array:", shape)
print("Size of num_array:", size)


Shape of num_array: (3, 3)
Size of num_array: 9


In [19]:
#Another way of performing Shape and Size of an array
num_array.shape

(3, 3)

In [20]:
num_array.size

9

In [21]:
# Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array
# creation function.
# [Hint: The size of the array will be 9 and the shape will be (3,3).]

In [22]:
import numpy as np

# Create a 3x3 matrix containing zeros
zeros_array = np.zeros((3, 3))

print(zeros_array)


[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [23]:
# Q6. Create an identity matrix of shape (5,5) using numpy functions?
# [Hint: An identity matrix is a matrix containing 1 diagonally and other elements will be 0.]

In [25]:
import numpy as np

# Create a 5x5 identity matrix
identity_matrix = np.eye(5)

print(identity_matrix)


[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [26]:
#Another way of performing  
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])